require "matt.options"
require "matt.plugins"
require "matt.keymaps"
require "matt.colorscheme"
require "matt.autopairs"
require "matt.nvim-tree"
require "matt.cmp"
require "matt.lsp"
require "matt.treesitter"
require "matt.telescope"

